# Generated by Django 3.0.3 on 2020-02-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=20, null=True)),
                ('plant_class', models.CharField(max_length=40, null=True)),
                ('plant_type', models.CharField(max_length=20, null=True)),
                ('active_nutrients', models.FloatField(default=0)),
                ('noactive_nutrients', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
