# Generated by Django 3.0.3 on 2020-02-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20200212_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'ordering': ['-created']},
        ),
    ]
